# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_controle.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, pyqtSignal
from PyQt5.QtWidgets import QApplication, QWidget, QTableWidget, QTableWidgetItem,QCheckBox, QMessageBox,QVBoxLayout
import sys
from bd import bd
from user_tele import Ui_Form_user_tele
from user_tele_cad import Ui_Form_user_tele_cad
from funcoes_tele import Ui_Form_funcoes_tele

class Ui_fundo(object):
    def setupUi(self, fundo):
        fundo.setObjectName("fundo")
        fundo.resize(995, 792)
        fundo.setMinimumSize(QtCore.QSize(700, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/soui/sou.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        fundo.setWindowIcon(icon)
        fundo.setStyleSheet("QWidget#fundo{\n"
"background-image: url(:/fundo/fundo.png)}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(fundo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu = QtWidgets.QFrame(fundo)
        self.menu.setStyleSheet("QFrame#menu{ \n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.menu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.frame_esquerdo = QtWidgets.QFrame(self.menu)
        self.frame_esquerdo.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_esquerdo.setStyleSheet("QFrame#frame_esquerdo{\n"
"    background-color: rgb(242, 242, 242);\n"
"\n"
"}")
        self.frame_esquerdo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_esquerdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_esquerdo.setObjectName("frame_esquerdo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_esquerdo)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_esquerdo)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_esquerdo)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buscar/buscar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_esquerdo)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.setColumnWidth(0, 10)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.frame_esquerdo, 1, 0, 1, 1)
        self.frame_painel = QtWidgets.QFrame(self.menu)
        self.frame_painel.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_painel.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_painel.setStyleSheet("QFrame#frame_painel{\n"
"    background-color: rgb(242, 242, 248);\n"
"}")
        self.frame_painel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_painel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_painel.setObjectName("frame_painel")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_painel)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_painel)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.var_titulo_menu = QtWidgets.QLabel(self.frame_2)
        self.var_titulo_menu.setGeometry(QtCore.QRect(30, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.var_titulo_menu.setFont(font)
        self.var_titulo_menu.setObjectName("var_titulo_menu")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame_painel)
        self.frame_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.var_mat = QtWidgets.QLabel(self.frame_3)
        self.var_mat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.var_mat.setObjectName("var_mat")
        self.gridLayout_4.addWidget(self.var_mat, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        self.var_user = QtWidgets.QLabel(self.frame_3)
        self.var_user.setObjectName("var_user")
        self.gridLayout_4.addWidget(self.var_user, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame_painel, 0, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.menu)

        self.retranslateUi(fundo)
        QtCore.QMetaObject.connectSlotsByName(fundo)

    def retranslateUi(self, fundo):
        _translate = QtCore.QCoreApplication.translate
        fundo.setWindowTitle(_translate("fundo", "Controle"))
        self.lineEdit.setPlaceholderText(_translate("fundo", "Buscar"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("fundo", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("fundo", "Nome"))
        self.var_titulo_menu.setText(_translate("fundo", "Controle das Funções bots"))
        self.var_mat.setText(_translate("fundo", "01"))
        self.label_3.setText(_translate("fundo", "-"))
        self.var_user.setText(_translate("fundo", "Adryan.silva"))
        self.pushButton.clicked.connect(self.buscartela)


        self.tableWidget.itemSelectionChanged.connect(self.onItemSelected)

        try:
            con = bd.conexao.conectarbot()
            cursor = con.cursor()
            sql = "SELECT id,nome,tela FROM bot_modulos"
            cursor.execute(sql)
            resultados = cursor.fetchall()
            print(resultados[0][2])
            self.tableWidget.setRowCount(len(resultados))
            for row,text in enumerate(resultados):
              for column,data in enumerate(text):
                self.tableWidget.setItem(row, column, QTableWidgetItem(str(data)))

        except Exception as E:
            print(str(E))
        finally:
            cursor.close()
            con.close()
    def buscartela(self):
        nome = self.lineEdit.text()
        try:
            con = bd.conexao.conectarbot()
            cursor = con.cursor()
            sql = f"SELECT id,nome,tela FROM bot_modulos where nome like '%{nome}%'"
            cursor.execute(sql)
            resultados = cursor.fetchall()
            print(resultados[0][2])
            self.tableWidget.setRowCount(len(resultados))
            for row,text in enumerate(resultados):
              for column,data in enumerate(text):
                self.tableWidget.setItem(row, column, QTableWidgetItem(str(data)))

        except Exception as E:
            print(str(E))
        finally:
            cursor.close()
            con.close()

    def onItemSelected(self):
        # Obtém a célula atualmente selecionada
        current_item = self.tableWidget.currentItem()
        #id_tela = current_item.text()
        id_tela = self.tableWidget.item(current_item.row(), 0).text()
        print("valor da tela")
        print(str(id_tela))
        if current_item is not None:
            row = current_item.row()
            col = current_item.column()
            try:
             con = bd.conexao.conectarbot()
             cursor = con.cursor()
             sql = f"SELECT id,nome,tela FROM bot_modulos where id = {id_tela} "
             cursor.execute(sql)
             resultados = cursor.fetchall()
             print(resultados[0][2])

             
             self.Form = QtWidgets.QWidget()
             v_tela_open = resultados[0][2]
             classe = globals().get(v_tela_open)
             print (v_tela_open)
             #self.ui = Ui_Form_user_tele()
             self.ui = classe()
             self.ui.setupUi(self.Form)
             self.Form.show()
            
 
            except Exception as E:
                print(str(E))
            finally:
                cursor.close()
                con.close()


import icons.buscar
import IMAGENS_DEV_ENERGY.fundo
import IMAGENS_DEV_ENERGY.soui


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fundo = QtWidgets.QWidget()
    ui = Ui_fundo()
    ui.setupUi(fundo)
    fundo.show()
    sys.exit(app.exec_())
